apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
    "kubernetes.io/ingress.class": nginx
  name: {{ .Chart.Name }}
spec:
  rules:
    - host: {{ .Values.env.vizzyUri.value }}
      http:
        paths:
          - backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.service.http.port }}
            path: /