language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.5'
env:
  global:
  - PGPORT=5432
services:
- postgresql
script:
- RAILS_ENV=ci_test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database vizzy_dev;' -U postgres
before_install:
- openssl aes-256-cbc -K $encrypted_fb8ebefd631f_key -iv $encrypted_fb8ebefd631f_iv
  -in secrets.yml.enc -out config/secrets.yml.enc -d
